ALTER TABLE `style_skill_productions` DROP CONSTRAINT `style_skill_productions_passed_evidence_ck`;--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `worker_id` varchar(64);--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `lease_id` varchar(64);--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `attempt` int unsigned;--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `aseprite_adapter_sha256` varchar(64);--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `aseprite_upload_id` varchar(64);--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `validation_upload_id` varchar(64);--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD `error_code` varchar(80);--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD CONSTRAINT `style_skill_productions_error_evidence_ck` CHECK (`style_skill_productions`.`status` not in ('failed', 'blocked') or ((`style_skill_productions`.`job_id` is null and `style_skill_productions`.`worker_id` is null and `style_skill_productions`.`lease_id` is null and `style_skill_productions`.`attempt` is null and `style_skill_productions`.`error_code` is null) or (`style_skill_productions`.`job_id` is not null and `style_skill_productions`.`worker_id` is not null and `style_skill_productions`.`lease_id` is not null and `style_skill_productions`.`attempt` is not null and `style_skill_productions`.`error_code` is not null)));--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD CONSTRAINT `style_skill_productions_passed_evidence_ck` CHECK (`style_skill_productions`.`status` <> 'passed' or (`style_skill_productions`.`job_id` is not null and `style_skill_productions`.`worker_id` is not null and `style_skill_productions`.`lease_id` is not null and `style_skill_productions`.`attempt` is not null and `style_skill_productions`.`model_call_id` is not null and `style_skill_productions`.`image_attempt_id` is not null and `style_skill_productions`.`aseprite_profile_id` is not null and `style_skill_productions`.`aseprite_binary_sha256` is not null and `style_skill_productions`.`aseprite_adapter_sha256` is not null and `style_skill_productions`.`aseprite_artifact_id` is not null and `style_skill_productions`.`aseprite_upload_id` is not null and `style_skill_productions`.`validation_artifact_id` is not null and `style_skill_productions`.`validation_upload_id` is not null and `style_skill_productions`.`error_code` is null));--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD CONSTRAINT `style_skill_productions_worker_id_workers_id_fk` FOREIGN KEY (`worker_id`) REFERENCES `workers`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD CONSTRAINT `style_skill_productions_attempt_lease_fk` FOREIGN KEY (`job_id`,`attempt`,`worker_id`,`lease_id`) REFERENCES `job_attempts`(`job_id`,`attempt`,`worker_id`,`lease_id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD CONSTRAINT `style_skill_productions_aseprite_upload_fk` FOREIGN KEY (`aseprite_upload_id`,`run_id`,`job_id`,`worker_id`,`lease_id`,`attempt`,`aseprite_artifact_id`) REFERENCES `artifact_upload_sessions`(`id`,`run_id`,`job_id`,`worker_id`,`lease_id`,`attempt`,`artifact_id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `style_skill_productions` ADD CONSTRAINT `style_skill_productions_validation_upload_fk` FOREIGN KEY (`validation_upload_id`,`run_id`,`job_id`,`worker_id`,`lease_id`,`attempt`,`validation_artifact_id`) REFERENCES `artifact_upload_sessions`(`id`,`run_id`,`job_id`,`worker_id`,`lease_id`,`attempt`,`artifact_id`) ON DELETE restrict ON UPDATE no action;